database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: toor
  url: jdbc:mysql://localhost/share_photo

logging:
  level: INFO

allowedGrantTypes:
  - password

bearerRealm: oauth2-provider

imagePath: /home/wahyuoi/temp2

